name: Unit tests
on:
  push: 
    branches: 
     - main


jobs:
  unit-tests: 
    name: Run unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
      DATABASE_URI: "sqlite:///test.db"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.5.13"
          enable-cache: true
          cache-dependency-glob: |
            requirements**.txt
            uv.lock

    - run: uv sync --all-extras --group dev
    - run: uv run pytest

